#!/bin/bash
# IIKO Data Sync - Quick Commands

echo "=== IIKO Data Sync - Быстрые команды ==="
echo ""
echo "1. Установка зависимостей:"
echo "   pip install -r requirements.txt"
echo ""
echo "2. Создание базы данных:"
echo "   createdb iiko_data"
echo "   psql -U postgres -d iiko_data -f migrations/002_create_products_table.sql"
echo ""
echo "3. Запуск веб-интерфейса:"
echo "   python run_web.py"
echo "   Открыть: http://localhost:8080"
echo ""
echo "4. Консольная синхронизация:"
echo "   python main.py"
echo ""
echo "5. Проверка API:"
echo "   python test_api.py"
echo ""
echo "6. Анализ структуры данных:"
echo "   python check_structure.py"
echo ""
echo "7. Просмотр логов:"
echo "   tail -f logs/sync_*.log"
echo ""
echo "=== Текущие задачи ==="
echo "- Улучшить дизайн интерфейса"
echo "- Добавить раздел подразделений"
echo "- Добавить раздел поставщиков"
echo "- Сделать интерфейс продакшн-ready"
